# Generated by Django 6.1 on 2026-09-04 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('driver_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('lname', models.CharField(max_length=128, verbose_name='Фамилия')),
                ('fname', models.CharField(max_length=128, verbose_name='Имя')),
                ('patronimyc', models.CharField(blank=True, max_length=128, null=True, verbose_name='Отчество')),
                ('phone', models.CharField(max_length=12, unique=True, verbose_name='Телефон')),
                ('car_model', models.CharField(max_length=128, verbose_name='Модель авто')),
                ('car_number', models.CharField(max_length=8, verbose_name='Номер авто')),
                ('status', models.CharField(choices=[('В ожидании', 'В ожидании'), ('В работе', 'В работе'), ('Вне работы', 'Вне работы')], default='В ожидании', max_length=16, verbose_name='Статус')),
                ('is_blacklist', models.BooleanField(default=False, verbose_name='В чёрном списке')),
            ],
            options={
                'verbose_name': 'Водитель',
                'verbose_name_plural': 'Водители',
                'db_table': 'drivers',
            },
        ),
    ]
