# Generated by Django 6.1 on 2026-09-04 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0002_driver'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('lname', models.CharField(max_length=128, verbose_name='Фамилия')),
                ('fname', models.CharField(max_length=128, verbose_name='Имя')),
                ('patronimyc', models.CharField(blank=True, max_length=128, null=True, verbose_name='Отчество')),
                ('phone', models.CharField(max_length=12, unique=True, verbose_name='Телефон')),
                ('is_blacklist', models.BooleanField(default=False, verbose_name='В чёрном списке')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'db_table': 'clients',
            },
        ),
    ]
