# Generated by Django 6.1 on 2026-09-07 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0003_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='is_archive',
            field=models.BooleanField(default=False, verbose_name='В архиве'),
        ),
    ]
