# Generated by Django 6.1 on 2026-09-07 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0004_driver_is_archive'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_archive',
            field=models.BooleanField(default=False, verbose_name='В архиве'),
        ),
    ]
