# Generated by Django 6.1 on 2026-09-08 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0005_user_is_archive'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('shift_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('start_shift', models.DateTimeField(verbose_name='Начало смены')),
                ('end_shift', models.DateTimeField(verbose_name='Конец смены')),
                ('closed_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_shifts', to=settings.AUTH_USER_MODEL, verbose_name='Закрыл пользователь')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='taxi.driver', verbose_name='Водитель')),
                ('opened_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opened_shifts', to=settings.AUTH_USER_MODEL, verbose_name='Открыл пользователь')),
            ],
            options={
                'verbose_name': 'Смена',
                'verbose_name_plural': 'Смены',
                'db_table': 'shifts',
            },
        ),
    ]
