# Generated by Django 6.1 on 2026-09-10 09:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0006_shift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='opened_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opened_shifts', to=settings.AUTH_USER_MODEL, verbose_name='Открыл пользователь'),
        ),
    ]
