# Generated by Django 6.1 on 2026-09-10 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0007_alter_shift_opened_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('district_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('base_coefficient', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
            options={
                'verbose_name': 'Район',
                'verbose_name_plural': 'Районы',
                'db_table': 'districts',
            },
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('street_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('district', models.ForeignKey(db_column='fk_district_id', on_delete=django.db.models.deletion.CASCADE, related_name='streets', to='taxi.district')),
            ],
            options={
                'verbose_name': 'Улица',
                'verbose_name_plural': 'Улицы',
                'db_table': 'streets',
            },
        ),
    ]
