# Generated by Django 6.1 on 2026-09-13 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0008_district_street'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('tariff_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('time_from', models.TimeField()),
                ('time_to', models.TimeField()),
                ('days_of_week', models.IntegerField(help_text='Битовая маска дней недели: Пн=1, Вт=2, Ср=4, Чт=8, Пт=16, Сб=32, Вс=64')),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифы',
                'db_table': 'tariffs',
            },
        ),
    ]
