# Generated by Django 6.1 on 2026-09-13 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0009_tariff'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariff',
            name='is_archive',
            field=models.BooleanField(default=False, verbose_name='В архиве'),
        ),
    ]
