# Generated by Django 6.1 on 2026-09-14 11:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0010_tariff_is_archive'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=16, unique=True, verbose_name='Номер заказа')),
                ('house_from', models.CharField(max_length=6, verbose_name='Номер дома (откуда)')),
                ('house_to', models.CharField(max_length=6, verbose_name='Номер дома (куда)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Цена')),
                ('status', models.CharField(choices=[('Новый', 'Новый'), ('Назначен водитель', 'Назначен водитель'), ('В работе', 'В работе'), ('Завершен', 'Завершен'), ('Отменен', 'Отменен')], default='Новый', max_length=32, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Время завершения')),
                ('client', models.ForeignKey(db_column='fk_client_id', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='taxi.client', verbose_name='Клиент')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_orders', to=settings.AUTH_USER_MODEL, verbose_name='Создал пользователь')),
                ('driver', models.ForeignKey(blank=True, db_column='fk_driver_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='taxi.driver', verbose_name='Водитель')),
                ('street_from', models.ForeignKey(db_column='street_from', on_delete=django.db.models.deletion.CASCADE, related_name='orders_from', to='taxi.street', verbose_name='Улица откуда')),
                ('street_to', models.ForeignKey(db_column='street_to', on_delete=django.db.models.deletion.CASCADE, related_name='orders_to', to='taxi.street', verbose_name='Улица куда')),
                ('tariff', models.ForeignKey(db_column='fk_tariff_id', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='taxi.tariff', verbose_name='Тариф')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'db_table': 'orders',
                'ordering': ['-created_at'],
            },
        ),
    ]
