# Generated by Django 6.1 on 2026-09-15 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0011_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Создание'), ('UPDATE', 'Изменение'), ('DELETE', 'Удаление'), ('LOGIN', 'Вход в систему'), ('LOGOUT', 'Выход из системы'), ('ASSIGN_DRIVER', 'Назначение водителя'), ('COMPLETE_ORDER', 'Завершение заказа'), ('CANCEL_ORDER', 'Отмена заказа'), ('TOGGLE_ARCHIVE', 'Архивирование'), ('TOGGLE_BLACKLIST', 'Чёрный список'), ('OTHER', 'Другое')], max_length=32, verbose_name='Действие')),
                ('object_type', models.CharField(blank=True, max_length=64, null=True, verbose_name='Тип объекта')),
                ('object_id', models.IntegerField(blank=True, null=True, verbose_name='ID объекта')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('extra_data', models.TextField(blank=True, null=True, verbose_name='Доп. данные')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Лог аудита',
                'verbose_name_plural': 'Логи аудита',
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
